[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.setuptools",
  "python311Packages.pip",
  "python311Packages.distutils",
  "gcc",
  "cmake",
  "libGL",
  "glib"
]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:5000"
