[phases.setup]
nixPkgs = ["python312", "gcc", "cmake", "python312Full", "libGL", "glib"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:5000"
